import obd
from influxdb.line_protocol import make_lines

def get_pts_name():
    """ Get file with pts_name generated by obdsim. """
    with open("../pty_name.txt", "r") as f:
        return str( f.read() )

def to_line_proto(measurement, fields={}, **tags):
    """ Convert a recorded value to influxdb LINE protocol. """

    return make_lines([{
        "measurement": measurement,
        "fields": fields,
        "tags": tags
        }])

def get_valid_modes():
    """ Return modes that have valid commands. """

    modes = obd.commands.modes
    non_empty_modes = [ mode for mode in modes if len( mode )]

    return [ [ command for command in mode if command ] for mode in non_empty_modes ]
